In [2]:
from pandas_datareader import data, wb
import pandas as pd
import numpy as np
import datetime
%matplotlib inline

In [6]:
start=datetime.datetime(2006,1,1)
end=datetime.datetime(2007,1,1)

In [11]:
#Bank of America
BAC = data.DataReader('BAC','robinhood',start,end)

In [12]:
# Get the general idea of the dataset
BAC.head()

                  close_price high_price  interpolated  low_price open_price  \
symbol begins_at
BAC    2017-08-14   24.004100  24.068000         False  23.758400  23.817400
       2017-08-15   24.053300  24.426800         False  24.033600  24.328500
       2017-08-16   23.778000  24.200700         False  23.669900  24.122100
       2017-08-17   23.237400  23.754900         False  23.217700  23.660100
       2017-08-18   23.217700  23.493000         False  23.050600  23.158800

                  session    volume
symbol begins_at
BAC    2017-08-14     reg  54989495
       2017-08-15     reg  45143228
       2017-08-16     reg  59188933
       2017-08-17     reg  78969326
       2017-08-18     reg  60461197

In [14]:
# CitiGroup
C = data.DataReader("C", 'robinhood', start, end)

# Goldman Sachs
GS = data.DataReader("GS", 'robinhood', start, end)

# JPMorgan Chase
JPM = data.DataReader("JPM", 'robinhood', start, end)

# Morgan Stanley
MS = data.DataReader("MS", 'robinhood', start, end)

# Wells Fargo
WFC = data.DataReader("WFC", 'robinhood', start, end)

In [15]:
WFC

                  close_price high_price  interpolated  low_price open_price  \
symbol begins_at
WFC    2017-08-14   51.396400  51.639500         False  50.910000  50.939200
       2017-08-15   51.406100  51.900400         False  51.386600  51.746500
       2017-08-16   51.250500  51.756300         False  51.026800  51.561700
       2017-08-17   50.384800  51.195500         False  50.375100  51.036500
       2017-08-18   50.268100  50.715500         False  49.976300  50.219400
       2017-08-21   50.404200  50.491800         False  49.995700  50.326400
       2017-08-22   50.793300  50.841900         False  50.501500  50.530700
       2017-08-23   50.608500  51.046200         False  50.384800  50.414000
       2017-08-24   50.734900  51.093700         False  50.613400  50.764100
       2017-08-25   50.355600  51.133700         False  50.345900  50.841900
       2017-08-28   50.219400  50.598800         False  50.015200  50.530700
       2017-08-29   50.015200  50.093000         False  49.733100  49.810900
       2017-08-30   49.956800  50.326400         False  49.801200  50.054100
       2017-08-31   49.674700  49.840100         False  49.480200  49.606600
       2017-09-01   49.577500  50.083300         False  49.538600  49.665000
       2017-09-05   48.731200  49.285700         False  48.400500  49.246700
       2017-09-06   48.517200  48.896600         False  48.206000  48.877100
       2017-09-07   48.322700  48.575600         False  47.923900  48.575600
       2017-09-08   48.225400  48.614500         False  48.079500  48.254600
       2017-09-11   49.275900  49.412100         False  48.575600  48.634000
       2017-09-12   50.161100  50.316700         False  49.451000  49.460700
       2017-09-13   50.054100  50.102700         False  49.781700  49.986000
       2017-09-14   49.888700  50.307000         False  49.684500  50.131900
       2017-09-15   50.248600  50.268100         False  49.849800  49.879000
       2017-09-18   51.269900  51.396400         False  50.200000  50.258300
       2017-09-19   51.902200  52.125900         False  51.094800  51.279600
       2017-09-20   52.281500  52.635500         False  51.824300  51.931300
       2017-09-21   52.583000  52.758100         False  52.057800  52.087000
       2017-09-22   52.767800  52.874800         False  52.281500  52.446900
       2017-09-25   52.553900  52.840800         False  52.087000  52.592800
...                       ...        ...           ...        ...        ...
       2018-06-29   55.037200  56.705000         False  55.007500  55.215900
       2018-07-02   55.910800  55.970400         False  54.669900  54.799000
       2018-07-03   55.156400  56.218600         False  55.027300  56.020100
       2018-07-05   54.838700  55.672600         False  54.650100  55.513800
       2018-07-06   55.484000  55.722100         False  54.630200  54.898300
       2018-07-09   56.357600  56.551200         False  55.603100  55.781800
       2018-07-10   56.208700  56.665300         False  55.930700  56.645500
       2018-07-11   55.662700  56.337700         False  55.573300  55.990300
       2018-07-12   55.623000  56.069700         False  55.196100  56.049800
       2018-07-13   54.957800  55.384700         False  53.240400  54.342300
       2018-07-16   56.576000  56.814200         False  55.226900  55.335100
       2018-07-17   56.149100  56.615700         False  56.020100  56.536300
       2018-07-18   56.159000  56.407200         False  55.732200  55.851300
       2018-07-19   55.920800  56.466800         False  55.613000  55.851300
       2018-07-20   56.000200  56.243400         False  55.444300  55.662700
       2018-07-23   57.578600  57.668000         False  55.891000  55.980300
       2018-07-24   57.926100  58.263600         False  57.429700  57.578600
       2018-07-25   57.807000  58.075000         False  57.429700  57.677900
       2018-07-26   57.886400  58.303300         False  57.772200  58.045200
       2018-07-27   58.204100  58.472100         False  57.737500  57.955900
       2018-07-30   58.065100  58.834500         False  57.876500  58.402600
       2018-07-31   56.873800  58.283500         False  56.784500  58.184200
       2018-08-01   57.231200  57.856600         False  56.794400  57.538900
       2018-08-02   57.866500  58.020400         False  56.665300  56.665300
       2018-08-03   58.402600  58.501900         False  57.608400  57.638200
       2018-08-06   58.462200  58.601200         False  57.770200  58.154400
       2018-08-07   58.392700  58.725300         False  58.273600  58.511800
       2018-08-08   58.760000  59.067700         False  58.333100  58.333100
       2018-08-09   58.440000  58.898000         False  58.400000  58.650000
       2018-08-10   58.050000  58.420000         False  57.380000  57.380000

                  session    volume
symbol begins_at
WFC    2017-08-14     reg  16313225
       2017-08-15     reg  11028101
       2017-08-16     reg  11224409
       2017-08-17     reg  16814287
       2017-08-18     reg  17130641
       2017-08-21     reg  13503090
       2017-08-22     reg  12984102
       2017-08-23     reg  10019524
       2017-08-24     reg  12345029
       2017-08-25     reg  15307840
       2017-08-28     reg  12425896
       2017-08-29     reg  10715516
       2017-08-30     reg  11427543
       2017-08-31     reg  25231147
       2017-09-01     reg  16217688
       2017-09-05     reg  31251308
       2017-09-06     reg  26854049
       2017-09-07     reg  23367261
       2017-09-08     reg  18975665
       2017-09-11     reg  17987052
       2017-09-12     reg  17129536
       2017-09-13     reg  12617331
       2017-09-14     reg  13739413
       2017-09-15     reg  28494345
       2017-09-18     reg  20943426
       2017-09-19     reg  17046989
       2017-09-20     reg  21560419
       2017-09-21     reg  16210868
       2017-09-22     reg  18047820
       2017-09-25     reg  11595884
...                   ...       ...
       2018-06-29     reg  43188081
       2018-07-02     reg  21204896
       2018-07-03     reg  12830436
       2018-07-05     reg  16788632
       2018-07-06     reg  12345931
       2018-07-09     reg  16683969
       2018-07-10     reg  15581357
       2018-07-11     reg  15641421
       2018-07-12     reg  18236134
       2018-07-13     reg  34302940
       2018-07-16     reg  25538677
       2018-07-17     reg  21649009
       2018-07-18     reg  19913894
       2018-07-19     reg  22219397
       2018-07-20     reg  17124459
       2018-07-23     reg  24584057
       2018-07-24     reg  27245014
       2018-07-25     reg  15506626
       2018-07-26     reg  14165306
       2018-07-27     reg  17616936
       2018-07-30     reg  22699873
       2018-07-31     reg  21633939
       2018-08-01     reg  19192778
       2018-08-02     reg  13489479
       2018-08-03     reg  13720359
       2018-08-06     reg  13360502
       2018-08-07     reg  13811287
       2018-08-08     reg  13779623
       2018-08-09     reg  15859809
       2018-08-10     reg  16170067

[251 rows x 7 columns]

In [16]:
MS

                  close_price high_price  interpolated  low_price open_price  \
symbol begins_at
MS     2017-08-14   45.591100  46.007700         False  45.267600  45.297000
       2017-08-15   45.512700  46.365500         False  45.512700  46.081200
       2017-08-16   45.101000  45.895000         False  45.007900  45.689100
       2017-08-17   44.199200  45.071600         False  44.140400  44.924600
       2017-08-18   44.493200  44.914800         False  43.978600  44.052100
       2017-08-21   43.797300  44.503000         False  43.650200  44.503000
       2017-08-22   44.669700  44.802000         False  44.042300  44.111000
       2017-08-23   44.895100  45.042200         False  44.218800  44.307000
       2017-08-24   45.091200  45.267600         False  44.826500  45.061800
       2017-08-25   45.032400  45.502900         False  44.826500  45.257800
       2017-08-28   44.581500  45.248000         False  44.228600  45.248000
       2017-08-29   44.454000  44.669700         False  43.466000  43.836500
       2017-08-30   44.757900  45.047100         False  44.532500  44.542300
       2017-08-31   44.601100  45.130400         False  44.493200  45.091200
       2017-09-01   45.277400  45.600900         False  44.405000  44.689300
       2017-09-05   44.003100  44.816700         False  43.836500  44.757900
       2017-09-06   44.179600  44.444200         False  43.861000  44.150200
       2017-09-07   43.199300  44.238400         False  42.973900  44.238400
       2017-09-08   43.140500  43.924700         False  43.081700  43.317000
       2017-09-11   44.267800  44.434400         False  43.542400  43.826700
       2017-09-12   44.846100  45.164700         False  44.444200  44.463800
       2017-09-13   45.306800  45.346100         False  44.659900  44.826500
       2017-09-14   45.502900  45.836200         False  45.395100  45.483300
       2017-09-15   45.679300  45.738200         False  45.228400  45.346100
       2017-09-18   46.385100  46.728200         False  45.826400  45.895000
       2017-09-19   46.728200  47.022300         False  46.223400  46.385100
       2017-09-20   46.943900  47.316300         False  46.385100  46.767400
       2017-09-21   47.306500  47.532000         False  46.522300  46.855600
       2017-09-22   47.267300  47.326100         False  46.787000  47.081100
       2017-09-25   46.796800  47.355600         False  46.591000  47.149700
...                       ...        ...           ...        ...        ...
       2018-06-29   47.121400  48.980500         False  47.101600  48.692200
       2018-07-02   47.439600  47.489300         False  46.490300  46.684000
       2018-07-03   46.743700  47.608600         False  46.664200  47.588700
       2018-07-05   46.425600  47.210900         False  46.127300  47.012100
       2018-07-06   46.813300  47.012100         False  46.008000  46.256600
       2018-07-09   48.125500  48.215000         False  47.012100  47.012100
       2018-07-10   47.817300  48.364100         False  47.708000  48.145400
       2018-07-11   47.469400  47.787500         False  47.305400  47.360000
       2018-07-12   47.737800  47.986300         False  47.519100  47.717900
       2018-07-13   47.797500  48.115600         False  47.199500  47.797500
       2018-07-16   48.612600  48.801500         False  47.916700  47.936600
       2018-07-17   48.891000  49.154600         False  48.205000  48.712000
       2018-07-18   50.262900  51.197400         False  49.755900  50.451800
       2018-07-19   49.557100  50.670500         False  49.487500  50.203200
       2018-07-20   49.974600  50.287700         False  49.298600  49.358200
       2018-07-23   50.441800  50.700300         False  49.954700  49.974600
       2018-07-24   50.680400  51.222200         False  50.541200  50.680400
       2018-07-25   50.740100  50.809600         False  50.108800  50.680400
       2018-07-26   50.690400  51.058200         False  50.620800  50.919000
       2018-07-27   50.750000  50.998500         False  50.426900  50.789800
       2018-07-30   50.900000  51.310000         False  50.430000  50.880000
       2018-07-31   50.560000  51.015000         False  50.220000  50.960000
       2018-08-01   50.180000  51.180000         False  50.040000  50.940000
       2018-08-02   49.810000  50.030000         False  49.250000  49.810000
       2018-08-03   49.910000  50.160000         False  49.730000  49.970000
       2018-08-06   49.990000  50.120000         False  49.570000  49.890000
       2018-08-07   50.130000  50.840000         False  50.100000  50.150000
       2018-08-08   50.120000  50.380000         False  49.960000  50.130000
       2018-08-09   49.440000  50.250000         False  49.410000  50.100000
       2018-08-10   48.390000  48.890000         False  48.140000  48.880000

                  session    volume
symbol begins_at
MS     2017-08-14     reg   7136346
       2017-08-15     reg   7663010
       2017-08-16     reg   8350802
       2017-08-17     reg   9426821
       2017-08-18     reg   7284026
       2017-08-21     reg   8501908
       2017-08-22     reg   7130726
       2017-08-23     reg   5464753
       2017-08-24     reg   6640733
       2017-08-25     reg   5659431
       2017-08-28     reg   6526699
       2017-08-29     reg   8776148
       2017-08-30     reg   5672867
       2017-08-31     reg   7890839
       2017-09-01     reg   7024739
       2017-09-05     reg   8735656
       2017-09-06     reg   6313230
       2017-09-07     reg  11538295
       2017-09-08     reg   8739832
       2017-09-11     reg   8017000
       2017-09-12     reg   8010993
       2017-09-13     reg   6637917
       2017-09-14     reg   7414125
       2017-09-15     reg   9113079
       2017-09-18     reg   7938043
       2017-09-19     reg   7999620
       2017-09-20     reg   8673623
       2017-09-21     reg   9503556
       2017-09-22     reg   6050036
       2017-09-25     reg   7205180
...                   ...       ...
       2018-06-29     reg  13442731
       2018-07-02     reg   8655098
       2018-07-03     reg   5037768
       2018-07-05     reg  10577345
       2018-07-06     reg   7226975
       2018-07-09     reg   9412496
       2018-07-10     reg   9238826
       2018-07-11     reg   6089496
       2018-07-12     reg   7774660
       2018-07-13     reg   9746979
       2018-07-16     reg   8723993
       2018-07-17     reg  11138345
       2018-07-18     reg  18407322
       2018-07-19     reg  11363567
       2018-07-20     reg   8902851
       2018-07-23     reg   7728944
       2018-07-24     reg   7254883
       2018-07-25     reg   7466198
       2018-07-26     reg   5525022
       2018-07-27     reg   7032615
       2018-07-30     reg  10123712
       2018-07-31     reg   9714906
       2018-08-01     reg   9194876
       2018-08-02     reg   7882660
       2018-08-03     reg   5426539
       2018-08-06     reg   5086939
       2018-08-07     reg   5632265
       2018-08-08     reg   5884075
       2018-08-09     reg   7583434
       2018-08-10     reg  14321552

[251 rows x 7 columns]

In [17]:
JPM

                  close_price  high_price  interpolated   low_price  \
symbol begins_at
JPM    2017-08-14   90.522500   90.923800         False   90.365900
       2017-08-15   90.757400   91.569700         False   90.679100
       2017-08-16   90.131000   91.246800         False   89.925500
       2017-08-17   88.721600   90.003800         False   88.574800
       2017-08-18   88.809700   89.592700         False   88.271400
       2017-08-21   88.702100   89.005500         False   88.242100
       2017-08-22   89.612300   89.759100         False   89.064200
       2017-08-23   89.719900   90.375700         False   88.907600
       2017-08-24   89.573100   90.160400         False   89.465500
       2017-08-25   89.935300   90.512700         False   89.847200
       2017-08-28   89.651400   90.228900         False   89.191400
       2017-08-29   89.162100   89.367600         False   88.388900
       2017-08-30   89.367600   89.920600         False   89.250200
       2017-08-31   88.956500   89.896100         False   88.868500
       2017-09-01   89.749300   90.395300         False   89.015300
       2017-09-05   87.605900   89.167000         False   87.130500
       2017-09-06   88.193100   88.591700         False   87.733100
       2017-09-07   86.646700   88.212700         False   86.206300
       2017-09-08   86.539100   87.517800         False   86.362900
       2017-09-11   87.879900   88.330200         False   87.057800
       2017-09-12   88.956500   89.308900         False   88.183300
       2017-09-13   89.211000   89.553600         False   88.398700
       2017-09-14   89.034800   89.582900         False   88.809700
       2017-09-15   89.671000   89.759100         False   88.829300
       2017-09-18   90.943400   91.153800         False   89.896100
       2017-09-19   91.941700   92.352700         False   90.551900
       2017-09-20   92.587600   93.262900         False   91.716500
       2017-09-21   93.008500   93.341200         False   92.186300
       2017-09-22   92.812700   92.959500         False   92.421200
       2017-09-25   92.117800   92.861700         False   91.462100
...                       ...         ...           ...         ...
       2018-06-29  103.636800  106.322200         False  103.587100
       2018-07-02  104.512100  104.522000         False  102.821200
       2018-07-03  103.050000  105.203300         False  102.960500
       2018-07-05  103.720000  104.380000         False  103.530000
       2018-07-06  104.060000  104.500000         False  102.200000
       2018-07-09  107.280000  107.460000         False  104.710000
       2018-07-10  106.620000  108.400000         False  106.530000
       2018-07-11  106.390000  107.060000         False  106.210000
       2018-07-12  106.850000  107.560000         False  105.970000
       2018-07-13  106.360000  107.800000         False  105.140000
       2018-07-16  110.580000  110.770000         False  106.980000
       2018-07-17  110.500000  110.930000         False  109.749900
       2018-07-18  111.530000  112.120000         False  110.200000
       2018-07-19  109.890000  111.090000         False  109.730000
       2018-07-20  111.280000  111.740000         False  109.780000
       2018-07-23  113.350000  114.240000         False  110.930000
       2018-07-24  114.150000  114.780000         False  113.420000
       2018-07-25  115.180000  115.520000         False  113.380000
       2018-07-26  114.850000  115.585000         False  114.581000
       2018-07-27  116.030000  116.300000         False  114.810000
       2018-07-30  116.730000  117.610000         False  116.060000
       2018-07-31  114.950000  117.080000         False  114.820000
       2018-08-01  115.660000  116.690000         False  115.280000
       2018-08-02  116.150000  116.250000         False  114.330000
       2018-08-03  117.090000  117.130000         False  115.940000
       2018-08-06  117.120000  117.530000         False  116.180000
       2018-08-07  117.550000  118.290000         False  117.330000
       2018-08-08  117.790000  118.268600         False  117.280000
       2018-08-09  116.880000  117.720000         False  116.695000
       2018-08-10  115.730000  115.950000         False  114.683900

                   open_price session    volume
symbol begins_at
JPM    2017-08-14   90.405100     reg  10994793
       2017-08-15   91.325100     reg   8812720
       2017-08-16   91.060800     reg  11085401
       2017-08-17   89.808000     reg  13837463
       2017-08-18   88.388900     reg  13040738
       2017-08-21   88.917400     reg  11502065
       2017-08-22   89.132700     reg   9211781
       2017-08-23   88.937000     reg   8811292
       2017-08-24   89.974400     reg   8623165
       2017-08-25   89.925500     reg  11794644
       2017-08-28   90.199500     reg   7292915
       2017-08-29   88.525900     reg  10886082
       2017-08-30   89.308900     reg   9165342
       2017-08-31   89.857000     reg  13217404
       2017-09-01   89.308900     reg   9815834
       2017-09-05   89.083800     reg  16897304
       2017-09-06   88.085500     reg  11845663
       2017-09-07   88.193100     reg  14592255
       2017-09-08   86.431400     reg  14242198
       2017-09-11   87.488400     reg  13219047
       2017-09-12   88.251900     reg  14003776
       2017-09-13   88.682500     reg  12485428
       2017-09-14   89.259900     reg  10562826
       2017-09-15   89.142500     reg  18171794
       2017-09-18   89.974400     reg  11318699
       2017-09-19   90.737800     reg  12626131
       2017-09-20   92.098300     reg  15311581
       2017-09-21   92.450600     reg  10851489
       2017-09-22   92.685500     reg   8358310
       2017-09-25   92.499500     reg  10463432
...                       ...     ...       ...
       2018-06-29  106.103400     reg  18492497
       2018-07-02  103.159400     reg  11130044
       2018-07-03  104.840300     reg   8311680
       2018-07-05  104.130000     reg  10723412
       2018-07-06  103.120000     reg  12146127
       2018-07-09  104.710000     reg  13900793
       2018-07-10  108.020000     reg  14575873
       2018-07-11  106.310000     reg  10186482
       2018-07-12  107.420000     reg  12456754
       2018-07-13  107.300000     reg  21251626
       2018-07-16  107.050000     reg  24662621
       2018-07-17  110.690000     reg  14821876
       2018-07-18  110.420000     reg  14244944
       2018-07-19  111.060000     reg  16775305
       2018-07-20  110.000000     reg  13538125
       2018-07-23  111.060000     reg  18140010
       2018-07-24  113.550000     reg  14000419
       2018-07-25  113.880000     reg  13331966
       2018-07-26  115.420000     reg  11897769
       2018-07-27  115.180000     reg  12776237
       2018-07-30  116.280000     reg  13411618
       2018-07-31  117.080000     reg  15843763
       2018-08-01  115.750000     reg  13531590
       2018-08-02  114.570000     reg  11058108
       2018-08-03  116.000000     reg  11016102
       2018-08-06  116.790000     reg   9857351
       2018-08-07  117.740000     reg  10562067
       2018-08-08  117.330000     reg   8997220
       2018-08-09  117.510000     reg   9694541
       2018-08-10  115.500000     reg  12630949

[251 rows x 7 columns]

In [18]:
GS

                  close_price  high_price  interpolated   low_price  \
symbol begins_at
GS     2017-08-14  224.450300  226.888700         False  223.400500
       2017-08-15  224.677400  227.658700         False  224.588500
       2017-08-16  222.722700  226.079200         False  222.120500
       2017-08-17  218.586300  223.088000         False  218.280300
       2017-08-18  219.307000  221.223200         False  217.727500
       2017-08-21  217.964400  219.553800         False  216.404600
       2017-08-22  220.718700  220.916100         False  218.497500
       2017-08-23  219.889500  221.933000         False  218.497500
       2017-08-24  220.136300  221.691100         False  219.741400
       2017-08-25  219.622900  222.070100         False  219.287300
       2017-08-28  217.530000  220.230000         False  216.059100
       2017-08-29  217.886600  218.055200         False  213.716300
       2017-08-30  220.323500  222.106500         False  218.015400
       2017-08-31  221.631000  222.373900         False  220.481900
       2017-09-01  223.750800  225.415000         False  221.423000
       2017-09-05  215.727200  221.888600         False  215.251700
       2017-09-06  216.767300  218.936700         False  215.558800
       2017-09-07  213.805500  216.747500         False  212.616800
       2017-09-08  215.162600  217.213100         False  213.369600
       2017-09-11  218.976300  219.798500         False  216.925800
       2017-09-12  223.820200  225.543800         False  219.927200
       2017-09-13  224.424400  224.999000         False  222.601800
       2017-09-14  224.711700  225.949900         False  223.919200
       2017-09-15  223.097100  225.068300         False  221.710300
       2017-09-18  225.385300  226.841400         False  223.532900
       2017-09-19  226.752300  227.966300         False  225.187200
       2017-09-20  227.624000  229.466500         False  226.346100
       2017-09-21  229.109800  229.912200         False  227.237700
       2017-09-22  228.852300  229.308000         False  226.722600
       2017-09-25  228.089600  229.674500         False  226.202700
...                       ...         ...           ...         ...
       2018-06-29  220.570000  225.170000         False  220.450000
       2018-07-02  223.260000  223.340000         False  218.890100
       2018-07-03  220.380000  224.640000         False  219.990000
       2018-07-05  220.740000  222.140000         False  219.780000
       2018-07-06  221.790000  223.200000         False  219.880000
       2018-07-09  227.990000  228.200000         False  223.000000
       2018-07-10  226.850000  228.870000         False  225.848600
       2018-07-11  225.660000  227.250000         False  225.200000
       2018-07-12  227.220000  227.800000         False  225.770100
       2018-07-13  226.410000  228.620000         False  223.930000
       2018-07-16  231.440000  231.440000         False  226.740000
       2018-07-17  231.020000  233.230000         False  226.870000
       2018-07-18  231.240000  233.720000         False  230.150000
       2018-07-19  229.630000  231.990000         False  228.980000
       2018-07-20  231.690000  232.050000         False  228.800000
       2018-07-23  233.760000  234.860000         False  231.720000
       2018-07-24  235.880000  237.480000         False  234.340000
       2018-07-25  236.690000  236.850000         False  233.950000
       2018-07-26  237.110000  238.335000         False  236.430000
       2018-07-27  237.640000  238.800000         False  235.990000
       2018-07-30  238.950000  239.730000         False  236.890000
       2018-07-31  237.430000  239.500000         False  236.550000
       2018-08-01  236.040000  239.400000         False  235.780000
       2018-08-02  233.990000  235.210000         False  232.770000
       2018-08-03  234.090000  235.520000         False  233.490000
       2018-08-06  235.930000  236.980000         False  234.030000
       2018-08-07  237.830000  239.460000         False  236.490000
       2018-08-08  236.370000  239.160000         False  236.230000
       2018-08-09  233.780000  236.845000         False  233.390000
       2018-08-10  229.610000  231.455000         False  228.110000

                   open_price session   volume
symbol begins_at
GS     2017-08-14  223.473000     reg  2266069
       2017-08-15  226.632000     reg  1867043
       2017-08-16  225.338800     reg  2393898
       2017-08-17  221.508500     reg  3460287
       2017-08-18  217.964400     reg  3149324
       2017-08-21  219.553800     reg  2203270
       2017-08-22  219.020700     reg  2021309
       2017-08-23  219.060200     reg  2568023
       2017-08-24  220.906300     reg  2263028
       2017-08-25  220.777900     reg  2232476
       2017-08-28  220.057300     reg  2641607
       2017-08-29  215.222000     reg  2369131
       2017-08-30  218.173900     reg  2411427
       2017-08-31  221.145600     reg  2240611
       2017-09-01  222.433400     reg  2346855
       2017-09-05  221.740000     reg  5646209
       2017-09-06  216.915900     reg  3613562
       2017-09-07  216.668200     reg  3594587
       2017-09-08  213.478600     reg  3120862
       2017-09-11  217.995600     reg  2971497
       2017-09-12  220.442300     reg  3745841
       2017-09-13  223.126800     reg  2383468
       2017-09-14  223.968800     reg  1986626
       2017-09-15  225.008900     reg  4365813
       2017-09-18  224.166900     reg  2466828
       2017-09-19  225.860800     reg  1858009
       2017-09-20  227.336700     reg  2682253
       2017-09-21  227.723000     reg  1800822
       2017-09-22  228.466000     reg  1861843
       2017-09-25  228.594700     reg  2261753
...                       ...     ...      ...
       2018-06-29  224.400000     reg  3389763
       2018-07-02  219.750000     reg  1723244
       2018-07-03  224.460000     reg  1204376
       2018-07-05  221.500000     reg  2218550
       2018-07-06  220.540000     reg  1844971
       2018-07-09  223.360000     reg  2743874
       2018-07-10  228.000000     reg  2524839
       2018-07-11  225.760000     reg  2527030
       2018-07-12  227.640000     reg  2223060
       2018-07-13  226.630000     reg  2540528
       2018-07-16  227.200000     reg  3271217
       2018-07-17  231.480000     reg  9280184
       2018-07-18  232.340000     reg  6149874
       2018-07-19  231.110000     reg  4638844
       2018-07-20  229.010000     reg  2680624
       2018-07-23  231.800000     reg  2788682
       2018-07-24  234.750000     reg  2887509
       2018-07-25  235.010000     reg  2174698
       2018-07-26  237.000000     reg  1885496
       2018-07-27  237.960000     reg  1995539
       2018-07-30  238.000000     reg  2454219
       2018-07-31  239.500000     reg  2504133
       2018-08-01  238.500000     reg  2510727
       2018-08-02  233.930000     reg  2580124
       2018-08-03  234.440000     reg  3053130
       2018-08-06  234.140000     reg  2259700
       2018-08-07  237.250000     reg  2399530
       2018-08-08  238.120000     reg  2522656
       2018-08-09  236.350000     reg  2952021
       2018-08-10  230.970000     reg  3863732

[251 rows x 7 columns]

In [19]:
C

                  close_price high_price  interpolated  low_price open_price  \
symbol begins_at
C      2017-08-14   66.589400  66.824800         False  66.118500  66.314700
       2017-08-15   66.667800  67.638900         False  66.579500  67.266100
       2017-08-16   66.412800  67.060200         False  66.098900  66.844400
       2017-08-17   65.324100  66.353900         False  65.235800  66.020500
       2017-08-18   65.304400  66.064600         False  64.912100  65.118100
       2017-08-21   64.686500  65.500600         False  64.598200  65.304400
       2017-08-22   65.569300  65.647700         False  64.980800  65.020000
       2017-08-23   65.942000  66.275500         False  64.941500  64.941500
       2017-08-24   66.393200  66.609000         False  65.667400  66.157800
       2017-08-25   66.550100  66.932600         False  66.412800  66.501100
       2017-08-28   66.510900  66.873800         False  66.138200  66.775700
       2017-08-29   66.187200  66.471700         False  65.235800  65.422100
       2017-08-30   66.707100  67.079800         False  66.393200  66.403000
       2017-08-31   66.726700  66.981700         False  66.447100  66.844400
       2017-09-01   67.266100  67.702800         False  66.677600  66.805100
       2017-09-05   65.873300  66.643300         False  65.476100  66.471700
       2017-09-06   66.030300  66.304900         False  65.569300  66.167600
       2017-09-07   64.794400  66.143100         False  64.426600  66.094000
       2017-09-08   64.902300  65.637900         False  64.609000  64.706100
       2017-09-11   66.412800  66.491300         False  65.098500  65.481000
       2017-09-12   67.472100  67.920800         False  66.795300  66.913000
       2017-09-13   68.060600  68.197900         False  67.148400  67.374000
       2017-09-14   67.913500  68.413700         False  67.884100  68.021400
       2017-09-15   67.717300  68.045900         False  67.584900  67.795800
       2017-09-18   69.247400  69.571100         False  67.942900  68.050800
       2017-09-19   69.786900  70.326400         False  68.953200  68.953200
       2017-09-20   70.091000  70.816800         False  69.463200  70.012500
       2017-09-21   70.385200  70.748100         False  69.786900  70.081100
       2017-09-22   70.032100  70.267500         False  69.649600  70.228300
       2017-09-25   69.482800  70.140000         False  68.973800  69.845700
...                       ...        ...           ...        ...        ...
       2018-06-29   66.500800  68.339200         False  66.461100  67.574100
       2018-07-02   66.739300  66.739300         False  65.527000  65.795300
       2018-07-03   65.646200  67.067200         False  65.527000  67.027500
       2018-07-05   66.143100  66.411400         False  65.805200  66.023800
       2018-07-06   66.719400  66.918200         False  65.487200  65.805200
       2018-07-09   68.508200  68.617500         False  67.067200  67.077200
       2018-07-10   67.802600  68.915600         False  67.524400  68.796300
       2018-07-11   67.484600  68.031200         False  67.415100  67.544200
       2018-07-12   68.080900  68.170300         False  67.514400  67.931800
       2018-07-13   66.580300  67.872200         False  65.805200  67.564100
       2018-07-16   69.024900  69.273300         False  66.858600  66.938100
       2018-07-17   68.915600  69.432300         False  68.369000  69.064700
       2018-07-18   69.412500  69.814900         False  68.786400  68.786400
       2018-07-19   68.557900  69.124300         False  68.125600  69.064700
       2018-07-20   68.786400  69.124300         False  68.100900  68.359100
       2018-07-23   69.770200  70.008700         False  68.577700  68.726800
       2018-07-24   70.624800  71.022300         False  69.849700  69.959000
       2018-07-25   71.270800  71.300600         False  70.306800  70.376400
       2018-07-26   70.893100  71.459600         False  70.803700  71.300600
       2018-07-27   71.240900  71.370100         False  70.714300  70.913000
       2018-07-30   71.837200  72.334000         False  71.350300  71.409900
       2018-07-31   71.439700  71.916700         False  71.176300  71.747700
       2018-08-01   71.479400  72.617300         False  71.449600  72.045900
       2018-08-02   71.390000  71.479400         False  70.575100  70.893100
       2018-08-03   72.390000  72.520000         False  71.570000  71.640000
       2018-08-06   72.400000  72.650000         False  71.930000  72.160000
       2018-08-07   72.410000  72.905000         False  72.390000  72.570000
       2018-08-08   72.890000  73.210000         False  72.060000  72.140000
       2018-08-09   71.980000  72.650000         False  71.890000  72.440000
       2018-08-10   70.260000  70.900000         False  69.900000  70.630000

                  session    volume
symbol begins_at
C      2017-08-14     reg  15120179
       2017-08-15     reg  15471998
       2017-08-16     reg  15064540
       2017-08-17     reg  14487868
       2017-08-18     reg  13628933
       2017-08-21     reg  15791091
       2017-08-22     reg  13246992
       2017-08-23     reg  10031623
       2017-08-24     reg  11524823
       2017-08-25     reg  11883138
       2017-08-28     reg  10797585
       2017-08-29     reg  12447985
       2017-08-30     reg   9152007
       2017-08-31     reg  12439281
       2017-09-01     reg  10720614
       2017-09-05     reg  17649476
       2017-09-06     reg  11849419
       2017-09-07     reg  20307814
       2017-09-08     reg  13437956
       2017-09-11     reg  17287005
       2017-09-12     reg  15495439
       2017-09-13     reg  17467281
       2017-09-14     reg  15022089
       2017-09-15     reg  18360910
       2017-09-18     reg  18027783
       2017-09-19     reg  15466007
       2017-09-20     reg  19788127
       2017-09-21     reg  11509157
       2017-09-22     reg  10446623
       2017-09-25     reg  10762772
...                   ...       ...
       2018-06-29     reg  23800869
       2018-07-02     reg  12699136
       2018-07-03     reg  12345990
       2018-07-05     reg  12359036
       2018-07-06     reg  13125735
       2018-07-09     reg  15148455
       2018-07-10     reg  17057664
       2018-07-11     reg  13262807
       2018-07-12     reg  13345165
       2018-07-13     reg  34003829
       2018-07-16     reg  26659911
       2018-07-17     reg  17262797
       2018-07-18     reg  16321163
       2018-07-19     reg  14833856
       2018-07-20     reg  11952629
       2018-07-23     reg  15763954
       2018-07-24     reg  21883786
       2018-07-25     reg  14199697
       2018-07-26     reg  11169192
       2018-07-27     reg  11158968
       2018-07-30     reg  16339108
       2018-07-31     reg  13608112
       2018-08-01     reg  13612224
       2018-08-02     reg  13248616
       2018-08-03     reg  13680049
       2018-08-06     reg  10121747
       2018-08-07     reg  12991146
       2018-08-08     reg  10180392
       2018-08-09     reg  11044203
       2018-08-10     reg  20240101

[251 rows x 7 columns]

In [26]:
tickers=['BAC','C','GS','JPM','MS','WFC']

tickers

['BAC', 'C', 'GS', 'JPM', 'MS', 'WFC']

In [30]:
BAC.reset_index(drop=True,  
C.reset_index(drop=True, inplace=True)
GS.reset_index(drop=True, inplace=True)
JPM.reset_index(drop=True, inplace=True)
MS.reset_index(drop=True, inplace=True)
WFC.reset_index(drop=True, inplace=True)

bank_stocks=pd.concat([BAC,C,GS,JPM,MS,WFC],axis=1,keys=tickers)

In [31]:
bank_stocks.head()

          BAC                                                                  \
  close_price high_price interpolated  low_price open_price session    volume
0   24.004100  24.068000        False  23.758400  23.817400     reg  54989495
1   24.053300  24.426800        False  24.033600  24.328500     reg  45143228
2   23.778000  24.200700        False  23.669900  24.122100     reg  59188933
3   23.237400  23.754900        False  23.217700  23.660100     reg  78969326
4   23.217700  23.493000        False  23.050600  23.158800     reg  60461197

            C                            ...            MS                   \
  close_price high_price interpolated    ...    open_price session   volume
0   66.589400  66.824800        False    ...     45.297000     reg  7136346
1   66.667800  67.638900        False    ...     46.081200     reg  7663010
2   66.412800  67.060200        False    ...     45.689100     reg  8350802
3   65.324100  66.353900        False    ...     44.924600     reg  9426821
4   65.304400  66.064600        False    ...     44.052100     reg  7284026

          WFC
  close_price high_price interpolated  low_price open_price session    volume
0   51.396400  51.639500        False  50.910000  50.939200     reg  16313225
1   51.406100  51.900400        False  51.386600  51.746500     reg  11028101
2   51.250500  51.756300        False  51.026800  51.561700     reg  11224409
3   50.384800  51.195500        False  50.375100  51.036500     reg  16814287
4   50.268100  50.715500        False  49.976300  50.219400     reg  17130641

[5 rows x 42 columns]

In [32]:
bank_stocks.columns.names=['Bank Ticker','Stock Info']

In [33]:
bank_stocks.head()

Bank Ticker         BAC                                                        \
Stock Info  close_price high_price interpolated  low_price open_price session
0             24.004100  24.068000        False  23.758400  23.817400     reg
1             24.053300  24.426800        False  24.033600  24.328500     reg
2             23.778000  24.200700        False  23.669900  24.122100     reg
3             23.237400  23.754900        False  23.217700  23.660100     reg
4             23.217700  23.493000        False  23.050600  23.158800     reg

Bank Ticker                     C                            ...     \
Stock Info     volume close_price high_price interpolated    ...
0            54989495   66.589400  66.824800        False    ...
1            45143228   66.667800  67.638900        False    ...
2            59188933   66.412800  67.060200        False    ...
3            78969326   65.324100  66.353900        False    ...
4            60461197   65.304400  66.064600        False    ...

Bank Ticker         MS                          WFC                          \
Stock Info  open_price session   volume close_price high_price interpolated
0            45.297000     reg  7136346   51.396400  51.639500        False
1            46.081200     reg  7663010   51.406100  51.900400        False
2            45.689100     reg  8350802   51.250500  51.756300        False
3            44.924600     reg  9426821   50.384800  51.195500        False
4            44.052100     reg  7284026   50.268100  50.715500        False

Bank Ticker
Stock Info   low_price open_price session    volume
0            50.910000  50.939200     reg  16313225
1            51.386600  51.746500     reg  11028101
2            51.026800  51.561700     reg  11224409
3            50.375100  51.036500     reg  16814287
4            49.976300  50.219400     reg  17130641

[5 rows x 42 columns]

In [35]:
for tick in tickers:
    print(tick,bank_stocks[tick]['close_price'].max())

BAC 32.706400
C 78.883600
GS 272.416700
JPM 99.832900
MS 58.283300
WFC 64.576800

In [37]:
bank_stocks.xs(key='close_price',axis=1,level='Stock Info').max()

Bank Ticker
BAC     32.7064
C       78.8836
GS     272.4167
JPM     99.8329
MS      58.2833
WFC     64.5768
dtype: float64

In [38]:
returns=pd.DataFrame()

In [39]:
for tick in tickers:
    returns[tick+'Return']=bank_stocks[tick]['close_price'].pct_change()

TypeError: unsupported operand type(s) for /: 'str' and 'float'